### ISSUE TITLE
getsockopt for SCTP_RESET_ASSOC returns -1515870811 for optval.

### ISSUE THREAD

**Issue by hoelscher** [sctplab/stream-reset-improved#25] opened 2016-05-30 10:46 UTC
on FreeBSD 10.3 getsockopt returns 0
see test
https://github.com/nplab/RFC6525_Testsuite/blob/master/api_tests/sctp-sr-api-ra/sctp-sr-api-ra-v-2-1.pkt

**Comment by tuexen** [comment] 2016-07-10 20:19
This is a bug, but not in the SCTP code. It is a bug in packetdrill. The problem is that one should not check optval if the `getsockopt()` call failed. This is fixed in https://github.com/nplab/packetdrill/commit/91fe3de621d32b0987a98429d3f4a9e414d414fc.

**Closed as completed by tuexen** 2016-07-10 20:19 UTC
Labels: invalid
